### ISSUE TITLE
Error adding video in local environment

### ISSUE THREAD

**Issue by infojunkie** [meedan/montage#5]
* In a project, search for videos
* Select a video and click "Add to project"
=> App shows "Error adding videos: " and the video is not added.

**Comment by infojunkie** [comment]
The backend log shows: 
```montage_1  | ERROR    2018-08-13 16:49:38,314 service.py:191] Encountered unexpected error from ProtoRPC method implementation: HttpError (<HttpError 403 when requesting https://www.googleapis.com/youtube/v3/videos?key=XXX&part=snippet%2CcontentDetails%2CrecordingDetails&id=YYY&alt=json returned "The request did not specify any referer. Please ensure that the client is sending referer or use the API Console to remove the referer restrictions.">)
montage_1  | Traceback (most recent call last):
montage_1  |   File "/app/parts/google_appengine/lib/protorpc-1.0/protorpc/wsgi/service.py", line 181, in protorpc_service_app
montage_1  |     response = method(instance, request)
montage_1  |   File "/app/appengine/src/greenday_api/api.py", line 176, in invoke_remote
montage_1  |     response = remote_method(service_instance, request)
```

**Comment by infojunkie** [comment]
The good news is that this does not happen on live.

**Comment by infojunkie** [comment]
The full error is:
```
{
 "error": {
  "errors": [
   {
    "domain": "usageLimits",
    "reason": "ipRefererBlocked",
    "message": "The request did not specify any referer. Please ensure that the client is sending referer or use the API Console to remove the referer restrictions.",
    "extendedHelp": "https://console.developers.google.com/apis/credentials?project=583467124136"
   }
  ],
  "code": 403,
  "message": "The request did not specify any referer. Please ensure that the client is sending referer or use the API Console to remove the referer restrictions."
 }
}
```

**Comment by infojunkie** [comment]
Fixed by _removing_ the Application Restrictions of the API Key that's used for the local environment. I had originally restricted the referrer to be `localhost:8080` on both API Key and OAuth 2.0 client ID, but it seems only OAuth 2.0 client ID restriction is needed.
